// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pb/games/xq/xq.proto

package xq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TablesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TablesRequest) Reset() {
	*x = TablesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_games_xq_xq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablesRequest) ProtoMessage() {}

func (x *TablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_games_xq_xq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablesRequest.ProtoReflect.Descriptor instead.
func (*TablesRequest) Descriptor() ([]byte, []int) {
	return file_pb_games_xq_xq_proto_rawDescGZIP(), []int{0}
}

type TablesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableIds []int64 `protobuf:"varint,1,rep,packed,name=tableIds,proto3" json:"tableIds,omitempty"`
}

func (x *TablesReply) Reset() {
	*x = TablesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_games_xq_xq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablesReply) ProtoMessage() {}

func (x *TablesReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_games_xq_xq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablesReply.ProtoReflect.Descriptor instead.
func (*TablesReply) Descriptor() ([]byte, []int) {
	return file_pb_games_xq_xq_proto_rawDescGZIP(), []int{1}
}

func (x *TablesReply) GetTableIds() []int64 {
	if x != nil {
		return x.TableIds
	}
	return nil
}

type MyStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MyStatusRequest) Reset() {
	*x = MyStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_games_xq_xq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStatusRequest) ProtoMessage() {}

func (x *MyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_games_xq_xq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStatusRequest.ProtoReflect.Descriptor instead.
func (*MyStatusRequest) Descriptor() ([]byte, []int) {
	return file_pb_games_xq_xq_proto_rawDescGZIP(), []int{2}
}

type MyStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *MyStatusResponse) Reset() {
	*x = MyStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_games_xq_xq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyStatusResponse) ProtoMessage() {}

func (x *MyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_games_xq_xq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyStatusResponse.ProtoReflect.Descriptor instead.
func (*MyStatusResponse) Descriptor() ([]byte, []int) {
	return file_pb_games_xq_xq_proto_rawDescGZIP(), []int{3}
}

func (x *MyStatusResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_pb_games_xq_xq_proto protoreflect.FileDescriptor

var file_pb_games_xq_xq_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x78, 0x71, 0x2f, 0x78, 0x71,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x78, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0b, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x4d, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x32, 0x74, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x78, 0x71, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x78, 0x71, 0x2e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08,
	0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x2e, 0x78, 0x71, 0x2e, 0x4d, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x78, 0x71, 0x2e, 0x4d, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x68, 0x74, 0x74, 0x70, 0x73,
	0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x7a,
	0x32, 0x30, 0x32, 0x30, 0x2f, 0x70, 0x65, 0x74, 0x74, 0x79, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x2f, 0x78, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_games_xq_xq_proto_rawDescOnce sync.Once
	file_pb_games_xq_xq_proto_rawDescData = file_pb_games_xq_xq_proto_rawDesc
)

func file_pb_games_xq_xq_proto_rawDescGZIP() []byte {
	file_pb_games_xq_xq_proto_rawDescOnce.Do(func() {
		file_pb_games_xq_xq_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_games_xq_xq_proto_rawDescData)
	})
	return file_pb_games_xq_xq_proto_rawDescData
}

var file_pb_games_xq_xq_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_games_xq_xq_proto_goTypes = []interface{}{
	(*TablesRequest)(nil),    // 0: xq.TablesRequest
	(*TablesReply)(nil),      // 1: xq.TablesReply
	(*MyStatusRequest)(nil),  // 2: xq.MyStatusRequest
	(*MyStatusResponse)(nil), // 3: xq.MyStatusResponse
}
var file_pb_games_xq_xq_proto_depIdxs = []int32{
	0, // 0: xq.Game.GetTables:input_type -> xq.TablesRequest
	2, // 1: xq.Game.MyStatus:input_type -> xq.MyStatusRequest
	1, // 2: xq.Game.GetTables:output_type -> xq.TablesReply
	3, // 3: xq.Game.MyStatus:output_type -> xq.MyStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_games_xq_xq_proto_init() }
func file_pb_games_xq_xq_proto_init() {
	if File_pb_games_xq_xq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_games_xq_xq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_games_xq_xq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_games_xq_xq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_games_xq_xq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_games_xq_xq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_games_xq_xq_proto_goTypes,
		DependencyIndexes: file_pb_games_xq_xq_proto_depIdxs,
		MessageInfos:      file_pb_games_xq_xq_proto_msgTypes,
	}.Build()
	File_pb_games_xq_xq_proto = out.File
	file_pb_games_xq_xq_proto_rawDesc = nil
	file_pb_games_xq_xq_proto_goTypes = nil
	file_pb_games_xq_xq_proto_depIdxs = nil
}
