// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xq

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameClient interface {
	GetTables(ctx context.Context, in *TablesRequest, opts ...grpc.CallOption) (*TablesReply, error)
	MyStatus(ctx context.Context, in *MyStatusRequest, opts ...grpc.CallOption) (Game_MyStatusClient, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (Game_LoginClient, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) GetTables(ctx context.Context, in *TablesRequest, opts ...grpc.CallOption) (*TablesReply, error) {
	out := new(TablesReply)
	err := c.cc.Invoke(ctx, "/xq.Game/GetTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) MyStatus(ctx context.Context, in *MyStatusRequest, opts ...grpc.CallOption) (Game_MyStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &Game_ServiceDesc.Streams[0], "/xq.Game/MyStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameMyStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_MyStatusClient interface {
	Recv() (*MyStatusResponse, error)
	grpc.ClientStream
}

type gameMyStatusClient struct {
	grpc.ClientStream
}

func (x *gameMyStatusClient) Recv() (*MyStatusResponse, error) {
	m := new(MyStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (Game_LoginClient, error) {
	stream, err := c.cc.NewStream(ctx, &Game_ServiceDesc.Streams[1], "/xq.Game/Login", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameLoginClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_LoginClient interface {
	Recv() (*MyStatusResponse, error)
	grpc.ClientStream
}

type gameLoginClient struct {
	grpc.ClientStream
}

func (x *gameLoginClient) Recv() (*MyStatusResponse, error) {
	m := new(MyStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility
type GameServer interface {
	GetTables(context.Context, *TablesRequest) (*TablesReply, error)
	MyStatus(*MyStatusRequest, Game_MyStatusServer) error
	Login(*LoginRequest, Game_LoginServer) error
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (UnimplementedGameServer) GetTables(context.Context, *TablesRequest) (*TablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTables not implemented")
}
func (UnimplementedGameServer) MyStatus(*MyStatusRequest, Game_MyStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method MyStatus not implemented")
}
func (UnimplementedGameServer) Login(*LoginRequest, Game_LoginServer) error {
	return status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_GetTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xq.Game/GetTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetTables(ctx, req.(*TablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_MyStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MyStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).MyStatus(m, &gameMyStatusServer{stream})
}

type Game_MyStatusServer interface {
	Send(*MyStatusResponse) error
	grpc.ServerStream
}

type gameMyStatusServer struct {
	grpc.ServerStream
}

func (x *gameMyStatusServer) Send(m *MyStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Game_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).Login(m, &gameLoginServer{stream})
}

type Game_LoginServer interface {
	Send(*MyStatusResponse) error
	grpc.ServerStream
}

type gameLoginServer struct {
	grpc.ServerStream
}

func (x *gameLoginServer) Send(m *MyStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xq.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTables",
			Handler:    _Game_GetTables_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MyStatus",
			Handler:       _Game_MyStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Login",
			Handler:       _Game_Login_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/games/xq/xq.proto",
}
